services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend

  frontend:
    image: node:22
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      WDS_SOCKET_PORT: "0"
    volumes:
      - ./frontend/:/home/node/app
    ports:
      - "3000:3000"
    command: npm start

  backend:
    build: ./backend
    image: todo-app/backend
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - "8001:3001"
    command: python src/server.py
    environment:
      DEBUG: "true"
    env_file:
      - ./.env
